chore: update packages
MapColonies/3d-ingestion-catalog pull request #46
Opened 2023-10-31 09:31 UTC by heliprokupetz14

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2023-10-31 14:15 UTC, netanelC requested changes

2023-10-31 14:15 UTC, netanelC commented on src/containerConfig.ts
> +  const metrics = new Metrics(attributes);
In boilerplate, the Metrics class does not require an attribute
```suggestion
  const metrics = new Metrics();
```

2023-11-01 15:16 UTC, RonitKissis approved these changes

2023-11-02 08:57 UTC, netanelC approved these changes

2023-11-02 08:58 UTC, merged