Classification from lookup
MapColonies/3d-ingestion-catalog pull request #48
Opened 2023-11-09 08:19 UTC by heliprokupetz14

Validate classification according to lookup-table

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✔                                                                       |

2023-11-09 10:10 UTC, netanelC requested changes
1. You are not using the error 'ServiceNotAvailable' which you created.
2. There is no special change in package.json, don't modify it
3. See the specific code changes I reviewed

2023-11-09 10:10 UTC, netanelC commented on tests/integration/metadata/controllers/metadataController.spec.ts
> +          expect(newResponse.status).toBe(httpStatusCodes.BAD_REQUEST);
Test also the text of the response and check if you got the expected text

2023-11-09 10:10 UTC, netanelC commented on tests/integration/metadata/controllers/metadataController.spec.ts
> +          mockAxios.get.mockResolvedValue({ data: [{ value: payload.classification }] as ILookupOption[] });
Unnecessary

2023-11-09 10:10 UTC, netanelC commented on tests/integration/metadata/controllers/metadataController.spec.ts
Remove empty line

2023-11-09 10:10 UTC, netanelC commented on tests/integration/metadata/controllers/metadataController.spec.ts
Remove empty line

2023-11-09 10:10 UTC, netanelC commented on tests/integration/metadata/controllers/metadataController.spec.ts
Remove empty line

2023-11-09 10:10 UTC, netanelC commented on tests/integration/metadata/controllers/metadataController.spec.ts
> +          mockAxios.get.mockResolvedValue({ data: [{ value: payload.classification }] as ILookupOption[] });
Remove empty line

2023-11-09 10:10 UTC, netanelC commented on tests/integration/metadata/controllers/metadataController.spec.ts
Add this:
```suggestion
    });
```

2023-11-09 10:10 UTC, netanelC commented on package.json
> +    "generate-files": "npm run bundleOpenApi && npm run genenpm run migration:runrate-record-entity",
Why did you touch this?

2023-11-09 10:10 UTC, netanelC commented on package.json
> +    "fakeDB": "docker-compose up -d && "
Why did you touch this?

2023-11-09 10:10 UTC, netanelC requested changes
1. You are not using the error 'ServiceNotAvailable' which you created.
2. There is no special change in package.json, don't modify it
3. See the specific code changes I reviewed

2023-11-09 11:18 UTC, heliprokupetz14 commented on src/metadata/controllers/metadataController.ts
> +      const result = await this.validateClassification(payload.classification);
throw error.

2023-11-09 11:27 UTC, heliprokupetz14 commented on tests/integration/metadata/controllers/metadataController.spec.ts
> +          const entity = { classification: 13 };
because this is invalid classification value

2023-11-09 11:29 UTC, heliprokupetz14 commented on package.json
> +    "generate-files": "npm run bundleOpenApi && npm run genenpm run migration:runrate-record-entity",
i havent :)

2023-11-12 09:51 UTC, netanelC commented on src/metadata/controllers/metadataController.ts
> +        throw new BadValues('classification is not a valid value!');
Insert also the valid values for more informative error log. You can look at ingestion-service for an example.
Do it also in validatePostValues

2023-11-12 11:19 UTC, netanelC requested changes

2023-11-12 12:12 UTC, netanelC approved these changes
Good Work

2023-11-13 14:32 UTC, RonitKissis approved these changes
good job

2023-11-13 14:55 UTC, merged